apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    mathcLabels:
      component: worker
  template:
    metadata:
      labels: worker
    spec:
      containers:
        - name: worker
          image: sprab/multi-worker
          

